[package]
name = "git-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
